### ISSUE TITLE
Issue on displaying test code and additional test context

### ISSUE THREAD

**Issue by hieuduyaccp** [adamgruber/mochawesome#138] opened 2017-03-02 07:49 UTC
If I set enableCode=false, then the Additional Test Context also hidden. Also, it's quite tricky to copy the text in the Additional Test Context as after selecting the text, the mouse up event will collapse the panel.

Expectation: Additional Test Context still displays even enableCode=false.

**Comment by adamgruber** [comment] 2017-03-03 14:24
This seems to be a duplicate of #132. Make sure you have the latest version of `mochawesome-report-generator` installed.

I'll have to look into the copying issue.

**Comment by hieuduyaccp** [comment] 2017-03-06 02:25
hi, i have tried mochawesome-report-generator version both 1.0.7 and 1.1.0 with enableCode=false. Additional Test Context also not display after clicking on tests. Can you please double check? 
(I used "mochawesome": "^2.0.4")

**Comment by adamgruber** [comment] 2017-03-06 14:13
I checked it this morning with a fresh install of mochawesome 2.0.4 and it works as expected for me. With `enableCode=false` you will still be able to expand tests that have context. Here's an example test I have:
```js
const should = require('should');
const addContext = require('mochawesome/addContext');

it('should have context', function () {
  (1+1).should.equal(2);
  addContext(this, 'context');
});
```
And the test command I'm using:
```bash
mocha --reporter mochawesome --reporter-options enableCode=false
```
And this is the report output with expanded test showing context:
![screen shot 2017-03-06 at 9 01 59 am](https://cloud.githubusercontent.com/assets/2378900/23612888/3132b40c-024b-11e7-8d5f-826b28421473.png)

**Comment by jkwohlfahrt** [comment] 2017-03-08 21:19
I'm actually running into this issue as well, even with the latest versions of mochawesome and mochawesome-report-generator installed. I also copied down the testy example, ran the test, and the report did not display the additional context.

**Comment by adamgruber** [comment] 2017-03-08 21:58
Hmm, that's strange. Can you give me some more details on your setup? OS? Node version? Steps taken to run tests? There's bound to be some inconsistency somewhere that may help explain the issue.

**Comment by hieuduyaccp** [comment] 2017-03-09 02:04
My setup:
* Mac OS Sierra 10.12.3
* Node 7.2.0
* npm 3.10.9

```json
{
"dependencies": {
    "atob": "^2.0.3",
    "babel-polyfill": "6.16.0",
    "babel-runtime": "6.11.6",
    "body-parser": "^1.15.2",
    "chai": "^3.4.1",
    "chai-files": "^1.4.0",
    "chai-fs": "^1.0.0",
    "chai-fs-latest": "^0.1.0",
    "chai-json-schema": "^1.4.0",
    "chai-properties": "^1.2.1",
    "chai-subset": "^1.3.0",
    "chakram": "^1.5.0",
    "country-data": "0.0.30",
    "express": "^4.14.0",
    "http-status-codes": "^1.0.6",
    "jsonminify": "^0.4.1",
    "lodash": "^4.17.3",
    "log": "^1.4.0",
    "mocha": "^3.2.0",
    "moment": "^2.11.2",
    "moment-timezone": "^0.5.0",
    "mustache": "^2.3.0",
    "numeral": "^2.0.3",
    "randomstring": "^1.1.5",
    "swagger-parser": "^3.4.1",
    "uuid-js": "^0.7.5"
  },
  "devDependencies": {
    "babel-core": "^6.6.5",
    "babel-loader": "^6.2.4",
    "babel-plugin-react-transform": "^2.0.2",
    "babel-preset-es2015": "^6.6.0",
    "babel-preset-react": "^6.5.0",
    "babel-preset-stage-0": "^6.5.0",
    "mochawesome": "^2.0.4",
    "mochawesome-report-generator": "^1.1.0"
  }
}
```

**Comment by adamgruber** [comment] 2017-03-09 13:53
@hieuduyaccp I see that you have both `mochawesome` and `mochawesome-report-generator` in your deps. Unless you are using the `marge` CLI tool directly, you only need to have `mochawesome` in your deps because it brings in `mochawesome-report-generator`. As you have it, there may be a version mismatch.

I suggest you remove `mochawesome-report-generator` from your deps, `rm -rf node_modules`, and then `npm install` to ensure you have the latest version.

**Comment by hieuduyaccp** [comment] 2017-03-10 02:08
@adamgruber hi I have tried and the issue still there. I have tried removing `mochawesome-report-generator` from deps and reinstall as suggested. Checking the version of `mochawesome-report-generator` and `mochawesome`, they have versions of 1.1.0 and 2.0.4 respectively.

**Comment by adamgruber** [comment] 2017-03-10 02:50
Try removing the `assets` folder from wherever you are saving your reports and re-run the tests.

**Comment by hieuduyaccp** [comment] 2017-03-13 05:03
@adamgruber oh thanks! That solved the problem.

**Comment by adamgruber** [comment] 2017-03-13 13:30
@hieuduyaccp Cool. I just released `mochawesome-report-generator` 1.1.1 which fixes the issue with assets and with selecting/copying text from the report.

**Closed by adamgruber** 2017-03-13 13:30 UTC
Labels: analysis, duplicate

**Comment by PrasannaGumpalli** [comment] 2017-09-01 04:55
@adamgruber : Please can you help me to resolve this issue. even I'm getting the following error:
 [mochawesome] Error adding context: Invalid test object. and I have done all the above. 

code:
var chakram = require("chakram"),expect = chakram.expect;
var testConfig=require("../config.json");
var log4js=require("log4js");
var logger=log4js.getLogger();
const addContext=require('mochawesome/addContext');
describe('Search',function() {
    it('SearchTV', function () {
        return chakram.get(testConfig.APP_SERVER + testConfig.Search + testConfig.API_KEY + testConfig.Query).then(function (response) {
            //console.log(response.body);
            expect(response).to.have.status(200);
            expect(response).to.have.json('items[0].itemId', 46784935);
            expect(response).to.have.json('items[1].itemId', 45161377);
            addContext(this, 'hi');
        });

    });
});

**Comment by quarrell** [comment] 2017-09-14 14:25
@adamgruber 
I faced with the similar problem( It doesn't work inside function. I solved this in next way (not sure that is right, but works):

describe('Search',function() {
it('SearchTV', function () {
**var func = this;**
return chakram.get(testConfig.APP_SERVER + testConfig.Search + testConfig.API_KEY + testConfig.Query).then(function (response) {
expect(response).to.have.status(200);
expect(response).to.have.json('items[0].itemId', 46784935);
expect(response).to.have.json('items[1].itemId', 45161377);
**addContext(func, 'hi');**
});
