### ISSUE TITLE
Reports html does not display well

### ISSUE THREAD

**Issue by jetlv** [adamgruber/mochawesome#200] opened 2017-11-01 02:59 UTC
Hi Adam,

I am facing a problem while using it. Here I attached the generated report files. See report.json, obviously there are test cases listed in the json file. But when I open the html file, nothing displayed. Why does this happen? Is it something related to Chinese?

Thanks!

[report.zip](https://github.com/adamgruber/mochawesome/files/1432967/report.zip)

**Comment by adamgruber** [comment] 2017-11-01 20:28
From what I can see, there's something not right with the output data. The stats are reporting that there were 9 failed tests, however the tests themselves were categorized as `skipped` not `failed`. This difference is why you are not able to see anything in the report.

If you open the console and manually set the `skipped` filter to true, you will see your tests displayed.
```js
// In your browser console
reportStore.showSkipped = true
```

I'm not sure why the data is incorrect. I would need some actual sample code to try to debug it. Can you put together a repo with some code (dummy data is ok) that reproduces this?

**Comment by jetlv** [comment] 2017-11-02 03:11
```
let expect = require('chai').expect;
let Promise = require('bluebird')
let webdriver = require("selenium-webdriver")
let by = webdriver.By
let common = require('../common')
let flow = require('../flow')
let dataProvider = require('../resources/dataProvider')
let fs = require('fs')


describe("测试组", async () => {

    before(function () {
        global.drivers = [];
    });

    after(function () {
        drivers.forEach(async (driver, index, array) => {
            try {
                await driver.quit()
            } catch (error) {
            }
        })
    })


    beforeEach(async function () {
        this.index = 1
    })

    afterEach(async function () {
        let currentTestName = this.currentTest.title
        await common.takeScreenShotInAfterHook(drivers, currentTestName)
    })

    let args = [
        {
            name: '测试用例1',
            home_url: dataProvider.MULTI_LANG_VER.cosplay.home_url.test_env.fr,
            test_email: dataProvider.MULTI_LANG_VER.cosplay.order_test_account.test_env.fr.email,
            test_password: dataProvider.MULTI_LANG_VER.cosplay.order_test_account.test_env.fr.password,
            test_product: dataProvider.MULTI_LANG_VER.cosplay.order_test_product.test_env.fr.id
        },
        {
            name: '测试用例2',
            home_url: dataProvider.MULTI_LANG_VER.cosplay.home_url.test_env.en,
            test_email: dataProvider.MULTI_LANG_VER.cosplay.order_test_account.test_env.en.email,
            test_password: dataProvider.MULTI_LANG_VER.cosplay.order_test_account.test_env.en.password,
            test_product: dataProvider.MULTI_LANG_VER.cosplay.order_test_product.test_env.en.id
        }
    ]

    args.forEach(function (arg, index, array) {

        it(arg.name, async function () {
            this.retries(1);
            let home_url = arg.home_url
            let email = arg.test_email
            let password = arg.test_password
            let product = arg.test_product
            
            let driver = await common.getChromeDriver()
            driver.name = arg.name
            drivers.push(driver)

            common.step.call(this, '访问到首页')
            await driver.get(home_url)

            common.step.call(this, '进入登录页')
            await common.waitFor(driver, by.css("#base_unlogin_li a:nth-child(2)"), 10)
            await common.click(driver, by.css("#base_unlogin_li a:nth-child(2)"))
            await common.waitFor(driver, by.css("input[name='loginusername']"), 5)

            common.step.call(this, '输入邮箱密码登录')
            await common.sendKey(driver, by.css("input[name='loginusername']"), email)
            await common.sendKey(driver, by.css("input[name='loginuserpass']"), password)
            await common.click(driver, by.css(".loginbut span"))

            common.step.call(this, '搜索商品')
            await common.waitFor(driver, by.css("#keyword"), 5)
            await common.sendKey(driver, by.css("#keyword"), product)
            await common.click(driver, by.css(".search_botton"))
            await common.waitFor(driver, by.css(".goods_item"), 5)

            common.step.call(this, '进入商品详情页')
            await common.click(driver, by.css(".goods_item"))
            await common.waitForVisibleAndThrowException(driver, by.css("#product_right h1"), 5)
            await common.waitForVisibleAndThrowException(driver, by.css("#addtobag span"), 5)

            common.step.call(this, '加入购物车，并且验证已加入购物车')
            await common.click(driver, by.css("#addtobag span"))
            await common.waitFor(driver, by.css(".pro_title"), 5)
            await common.waitFor(driver, by.css(".product_num"), 5)
            await common.waitFor(driver, by.css(".cusbutton"), 5)

            common.step.call(this, 'Checkout')
            await common.click(driver, by.css(".cusbutton"))
            await common.waitFor(driver, by.css(".shopleft_box .submitbtn"), 5)

            common.step.call(this, '下单')
            await common.click(driver, by,css(".shopleft_box .submitbtn"))
            await common.waitFor(driver, by.css("#orderDetails .cartform tr:nth-child(1) td:nth-child(2)"))

            common.step.call(this, '验证产生订单')
            let orderCid = await common.getText(driver, by.css("#orderDetails .cartform tr:nth-child(1) td:nth-child(2)"))
            expect(orderCid.match(/_c1_/), '不正确的订单号码').is.not.null
        })
    })
})
```

Hi Adam, 

I attached my code above.  There is an intended reference error I made.  And then I tested again and noticed that this is due to mocha `retry` functionality, maybe this can save your time for debugging. When I removed `this.retries(1)` above, your report is working well. But when it comes to retrying, there is a bug I guess.

Also attached report zip.

Best,
Jet
[report.zip](https://github.com/adamgruber/mochawesome/files/1436361/report.zip)

**Comment by adamgruber** [comment] 2018-02-02 16:01
I believe the issue is related to mocha retries so I'm going close this as a duplicate of #125

**Closed by adamgruber** 2018-02-02 16:01 UTC
