### ISSUE TITLE
Code transforms to something ugly

### ISSUE THREAD

**Issue by trszdev** [adamgruber/mochawesome#232] opened 2018-03-11 21:06 UTC
Original code:
![untitled](https://user-images.githubusercontent.com/9008471/37258439-e7ba571c-2599-11e8-8051-87289732cb37.png)

Code in html:
![download](https://user-images.githubusercontent.com/9008471/37258435-df5b9bda-2599-11e8-9125-65b319549833.jpg)

**Comment by adamgruber** [comment] 2018-03-14 04:03
The reporter sees the code that mocha sees. Looks like you are running your code through some kind of transformer before running the tests. Maybe Babel? 

Possible duplicate of #202

**Comment by trszdev** [comment] 2018-03-18 03:24
Ok, im running node v9.7.1, with babel-es2015 (using only imports and exports statements). But why destructing is broken? And what should I do with (0, chai.expect)(...) ? Is there any solution&

**Comment by trszdev** [comment] 2018-03-18 03:25
Is there any option to see only original code of tests?

**Comment by adamgruber** [comment] 2018-06-03 23:09
Not really. If you transpile the code, that's what mocha sees.

**Closed by adamgruber** 2018-06-03 23:09 UTC
