### ISSUE TITLE
Cross domain links

### ISSUE THREAD

**Issue by legacyWork** [adamgruber/mochawesome#136] opened 2017-03-01 18:04 UTC
Mochawesome turns link info into links.

I though it was a CSP thing so i used 

System.setProperty("hudson.model.DirectoryBrowserSupport.CSP", "child-src 'https://www.browserstack.com*'; frame-src ‘unsafe-inline’ https://www.browserstack.com*; ‘sandbox allow-forms allow-scripts; default-src 'unsafe-inline'; img-src 'self' 'unsafe-inline';script-src 'self' 'unsafe-inline' 'unsafe-eval' https://www.browserstack.com*; style-src 'self' 'unsafe-inline'; connect-src ‘unsafe-inline’ font-src 'self' 'data';")

Jenkins  still doesn't like links in the report and fails when trying to render https://www.browserstack.com/automate/builds/

Uncaught DOMException: Blocked a frame with origin "null" from accessing a cross-origin frame.
    at Object.i.addEvent (http://jenkins.legacyobit.int:8080/job/BrowseAutoTestPipeLine2/Automated_Test_Report/mochawesome.html:63436:20238)

Is there a way to turn off the link transforming functionality?

**Comment by adamgruber** [comment] 2017-03-03 14:28
Are you referring to links that are used along with `addContext()`? I'm not really following what the issue is.

**Comment by adamgruber** [comment] 2017-04-19 17:49
Closing this issue for the following reason:
- No feedback for more than 30 days

If you are still experiencing this issue, please reopen and provide additional details.

**Closed by adamgruber** 2017-04-19 17:49 UTC
