### ISSUE TITLE
mochawesome report with the same testcase file path

### ISSUE THREAD

**Issue by onetrees2011** [adamgruber/mochawesome#135] opened 2017-02-25 02:25 UTC
HI,
There is a problem with both the old and the newest versions,the problem is that all the testcases's path  in one mochawesome report are the same as the first testcase's file path(for example ,the sample report in readme). is there a way to prevent this and have corresponding file path with the testcase ?

**Comment by adamgruber** [comment] 2017-02-27 15:22
Are you talking about the filename that is displayed under the Suite title? In my tests the correct pathnames are shown.

![screen shot 2017-02-27 at 10 24 08 am](https://cloud.githubusercontent.com/assets/2378900/23366940/982130a0-fcd6-11e6-9737-fe87bb0a2910.png)

If you want to put together a sample repo that exhibits this behavior then I can take a look.

**Comment by onetrees2011** [comment] 2017-02-28 08:19
i cant't upload the picture on some reasons,but that's what you mean . the codes  are as follows:
`var Mocha = require('mocha'),
    fs = require('fs'),
    path = require('path');

// Instantiate a Mocha instance.
var testFileDirs = ['test'];  //include many *.js testcases 
var testReporterNameHead = 'mochawesome_';
var testReporterName = testReporterNameHead;
var testReportDir = 'mochawesome-reports';
var testReportTitle = 'WebUI Test report';
var root_path=__dirname;
var totalFail = 0;

var mocha = new Mocha({
    reporter: 'mochawesome',
    reporterOptions: {
      reportDir: testReportDir,
      reportName: testReporterName,
      reportTitle: testReportTitle,
      inlineAssets: true
    }
});

// Add each .js file to the mocha instance
testFileDirs.forEach(function(item){
	var itemPath = root_path+"/"+item;
	if(item === '*')
		itemPath = root_path;
	getAllFiles(itemPath).filter(function(file){
		// Only keep the .js files
		var excludeFiles=[__filename,'UI_button_target.js'];
		return ((file.substr(-3) === '.js') && (excludeFiles.indexOf(file)=== -1));
	}).forEach(function(file){
		mocha.addFile(file);
	}); 
});

mocha.run()
    .on('fail', function(test,err) {
		totalFail++;
		console.log('error = '+err);
    })
	.on('end', function() {
        console.log('All done');
		process.exit(0);
    });
	`
testcases are as follows:

**Comment by adamgruber** [comment] 2017-02-28 14:31
Thanks for the code. I'll have look further into this when I have some time. I suspect its an issue with running mocha like this since the reporter only displays data that mocha returns. I'm curious why you are calling mocha like this versus just using the command line and pointing to a folder? If you need to exclude certain files you can also use mocha's `--grep` option to define a pattern.

**Comment by niklasdoerfler** [comment] 2017-03-20 06:50
Hi,
I've got the same problem mentioned above.
I'm running mocha from command line like this: `mocha test --reporter mochawesome`. The folder 'test' contains my testfiles which are compiled from typescript. 
Did you find a solution for this already?

**Comment by adamgruber** [comment] 2017-06-09 02:42
Closing for now since I cannot reproduce the issue. Feel free to reopen and provide some sample code that illustrates the problem.

**Closed by adamgruber** 2017-06-09 02:42 UTC

**Comment by MeikeMertschFortum** [comment] 2021-08-01 09:05
I have the same issue and it just struck me that when I search for "file" in this repository, I find this:
<img width="423" alt="Screenshot 2021-08-01 at 11 02 41" src="https://user-images.githubusercontent.com/61452719/127765488-32ed8135-4ce9-43fa-976c-5faa08bee9ee.png">
And I wonder if the reason is, that my files are type script. I am still learning JS and TS, so I have real trouble with "just trying it out". But can I just ask: will that work for typescript tests as well? Because I REALLY want that as well so I don't have to bend over backwards to get that information somehow into the title.

Thanks!!

**Comment by adamgruber** [comment] 2021-09-11 13:41
@MeikeMertschFortum That code snippet you shared comes from one of the tests in this library and is not related to the actual code of library.
