### ISSUE TITLE
Problem with mochawesome: TypeError: Cannot read properties of undefined (reading 'length')

### ISSUE THREAD

**Issue by quad5** [adamgruber/mochawesome#373] opened 2022-03-17 18:36 UTC
**Describe the bug**

I am using Cypress, and I am not sure whose bug this belongs to. What is happening is that it seems like html file isn't generated when I am running more than 1 spec file.

**Code Reproduce**
Link to repo where the issue can reliably be reproduced:

**Expected behavior**

**Screenshots**

<img width="1300" alt="image" src="https://user-images.githubusercontent.com/2043287/158869769-1376df87-367c-48ee-bc81-a995ec64f412.png">

<img width="370" alt="image" src="https://user-images.githubusercontent.com/2043287/158871196-b6ab3eeb-0e89-433b-932b-771104869e9c.png">

**Environment (please complete the following information):**
 - Platform
 - mochawesome version
          "cypress-mochawesome-reporter": "3.0.0",
          "mochawesome": "7.1.2"
 - mocha (or other test library) version
         mocha: 9.2.2
 - Node version
         Node:  16.5.0

**Additional context**

**Comment by adamgruber** [comment] 2022-03-22 14:55
Please provide steps to reproduce.

**Comment by jaltmanQ** [comment] 2022-03-23 12:40
Ran into this issue myself.  The problem was a utility file in the cypress/integration folder that had no tests in it.

**Comment by Idleness76** [comment] 2022-03-24 12:56
> Ran into this issue myself. The problem was a utility file in the cypress/integration folder that had no tests in it.

@jaltmanQ - I'm seeing a similar error and I do not have a cypress/integration folder present at all.


@adamgruber - This problem seems to be occurring not just with multiple spec files - but instead (for me at least), this happens when tests may not be run even though Cypress sees them.  I'll try to explain concisely.  In my project I have setup spec files to have tags and when Cypress is run, I specify 1 or more tags.  If multiple spec files exist AND the tags match all spec files present, then the reports are generated without any issue.  Even if some files don't actually run tests.  I verified that by including a spec file with 1 test, and marked it as it.skip().

The more specific problem, when I see this error, is when there are multiple spec files present but the used tag means that Cypress will skip over 1 or more.  This is the case when the error occurs for me.  This is new behaviour - but I'm not certain how recent as I've unfortunately just upgraded from versions I was using a few months ago.

I can say with some conviction that before making upgrades to several packages recently -  cypress-mochawesome-reporter included - that this problem did not exist and no errors were generated when spec files were present that were skipped over.

**Comment by adamgruber** [comment] 2022-03-25 13:33
Released 7.1.3 to address this issue.

**Closed by adamgruber** 2022-03-25 13:33 UTC
Labels: investigating
