### ISSUE TITLE
How to addContext globally

### ISSUE THREAD

**Issue by gkvappium** [adamgruber/mochawesome#235] opened 2018-03-28 04:52 UTC
I have a scenario wherein I have multiple test case files which can be executed in any order (Mocha test framework). So I need to add some context that is for the entire report.

The test case files are executed one after the other and the reporter shows one consolidated report. So this context should be displayed at the top of the report which is not specific to any particular test case file. But is common to all.

Also please let me know if there is a way to add tables so that the added context gets into the table

**Comment by gkvappium** [comment] 2018-03-29 06:29
@adamgruber , any thoughts on this?

**Comment by adamgruber** [comment] 2018-03-29 17:42
There is currently no way to add anything to the report outside of test context.

Adding tables in context is also not currently available but I'd like to see an example of what you'd like to display. This could be added in a future release.

**Comment by gkvappium** [comment] 2018-03-30 05:16
Thanks @adamgruber . Basically I am using this for IOS and Android automation. I just want to include the capabilities that I pick up from the file and show it in the report so that when ppl see the report, they get to know the details of the phone and other relevant things. Please see the below example. I also wanted to have this globally since I have more than 1 test file and all these are relevant to the entire report. 

    "android19": {
        "platformName": "Android",
        "platformVersion": "7.0",
        "deviceName": "Galaxy S8",
        "lt": 60000,
        "appPackage": "com.xyz.abc.control",
        "newCommandTimeout": 720,
        "noReset": true,
        "automationName": "uiautomator2",
        "fullReset": false,
        "app": "/Users/Downloads/app-debug.apk"

**Comment by adamgruber** [comment] 2018-04-03 14:38
Duplicate of #174

**Closed by adamgruber** 2018-04-03 14:38 UTC
Labels: enhancement
