### ISSUE TITLE
Incorrect report data when mocha retries enabled

### ISSUE THREAD

**Issue by ethangodt** [adamgruber/mochawesome#190] opened 2017-09-18 23:33 UTC
When we run tests with mocha retries enabled *and* a test fails the `suites` data generated in the report shows that the test was skipped instead of failed (all other properties of the report correctly show it as having failed).

This results in the `.html` page looking like (with no ability to change the toggles to show the failing tests):
![image](https://user-images.githubusercontent.com/11809142/30571199-f0f61678-9c9a-11e7-9b7e-6b4ed49b225a.png)

I know this isn't a lot of information, so I'm happy to provide whatever else would make this easier to track down. Below is an example of the issue (file name and titles have been altered).

```
{
  "stats": {
    "suites": 1,
    "tests": 1,
    "passes": 0,
    "pending": 0,
    "failures": 1,
    "start": "2017-09-18T23:16:56.175Z",
    "end": "2017-09-18T23:17:27.574Z",
    "duration": 31399,
    "testsRegistered": 1,
    "passPercent": 0,
    "pendingPercent": 0,
    "other": 0,
    "hasOther": false,
    "skipped": 0,
    "hasSkipped": false,
    "passPercentClass": "danger",
    "pendingPercentClass": "danger"
  },
  "suites": {
    "title": "",
    "suites": [
      {
        "title": "suite title 1",
        "suites": [],
        "tests": [
          {
            "title": "suite title 1",
            "fullTitle": "suite title 1",
            "timedOut": false,
            "duration": 9101,
            "pass": false,
            "fail": false,
            "pending": false,
            "code": "step(\"throw\", err); }); } } return step(\"next\"); });",
            "err": {},
            "isRoot": false,
            "uuid": "31b95db9-7879-4785-aab7-6d493d6a7edb",
            "parentUUID": "26fe76b2-d17f-4272-a04f-249eaaf602ba",
            "isHook": false,
            "skipped": true
          }
        ],
        "pending": [],
        "root": false,
        "_timeout": 480000,
        "file": "filename.js",
        "uuid": "26fe76b2-d17f-4272-a04f-249eaaf602ba",
        "beforeHooks": [
          {
            "title": "\"before all\" hook: checkNemo",
            "fullTitle": "title",
            "timedOut": false,
            "duration": 14694,
            "pass": false,
            "fail": false,
            "pending": false,
            "code": "function checkNemo(_done) {\n        Nemo(config).then(function (_nemo) {\n          nemo = _nemo;\n          _done();\n        }).catch(function (err) {\n          error(err);\n          _done(err);\n          if (done) {\n            done(result);\n          }\n        });",
            "err": {},
            "isRoot": false,
            "uuid": "c7d50765-ad88-4929-8794-ebc57fb2bf4e",
            "parentUUID": "26fe76b2-d17f-4272-a04f-249eaaf602ba",
            "isHook": true,
            "skipped": false
          }
        ],
        "afterHooks": [],
        "fullFile": "title",
        "passes": [],
        "failures": [],
        "skipped": [
          {
            "title": "test title 1",
            "fullTitle": "test title 1",
            "timedOut": false,
            "duration": 9101,
            "pass": false,
            "fail": false,
            "pending": false,
            "code": "step(\"throw\", err); }); } } return step(\"next\"); });",
            "err": {},
            "isRoot": false,
            "uuid": "31b95db9-7879-4785-aab7-6d493d6a7edb",
            "parentUUID": "26fe76b2-d17f-4272-a04f-249eaaf602ba",
            "isHook": false,
            "skipped": true
          }
        ],
        "hasBeforeHooks": true,
        "hasAfterHooks": false,
        "hasTests": true,
        "hasSuites": false,
        "totalTests": 1,
        "totalPasses": 0,
        "totalFailures": 0,
        "totalPending": 0,
        "totalSkipped": 1,
        "hasPasses": false,
        "hasFailures": false,
        "hasPending": false,
        "hasSkipped": true,
        "duration": 9101,
        "rootEmpty": false
      }
    ],
    "tests": [],
    "pending": [],
    "root": true,
    "_timeout": 480000,
    "uuid": "c37788b8-0b57-4907-ad4f-cd20eb894244",
    "beforeHooks": [],
    "afterHooks": [],
    "fullFile": "",
    "file": "",
    "passes": [],
    "failures": [],
    "skipped": [],
    "hasBeforeHooks": false,
    "hasAfterHooks": false,
    "hasTests": false,
    "hasSuites": true,
    "totalTests": 0,
    "totalPasses": 0,
    "totalFailures": 0,
    "totalPending": 0,
    "totalSkipped": 0,
    "hasPasses": false,
    "hasFailures": false,
    "hasPending": false,
    "hasSkipped": false,
    "duration": 0,
    "rootEmpty": true
  },
  "allTests": [
    {
      "title": "test title 1",
      "fullTitle": "test title 1",
      "timedOut": false,
      "duration": 7520,
      "state": "failed",
      "pass": false,
      "fail": true,
      "pending": false,
      "code": "step(\"throw\", err); }); } } return step(\"next\"); });",
      "err": {
        "message": "StatusCodeError: 500",
        "estack": "StatusCodeError: 500"
      },
      "isRoot": false,
      "uuid": "7f797ca2-a693-4233-8e07-8cbb1fe9a3be",
      "parentUUID": "26fe76b2-d17f-4272-a04f-249eaaf602ba",
      "isHook": false,
      "skipped": false
    }
  ],
  "allPending": [],
  "allPasses": [],
  "allFailures": [
    {
      "title": "test title 1"",
      "fullTitle": "test title 1",
      "timedOut": false,
      "duration": 7520,
      "state": "failed",
      "pass": false,
      "fail": true,
      "pending": false,
      "code": "step(\"throw\", err); }); } } return step(\"next\"); });",
      "err": {
        "message": "StatusCodeError: 500",
        "estack": "StatusCodeError: 500"
      },
      "isRoot": false,
      "uuid": "7f797ca2-a693-4233-8e07-8cbb1fe9a3be",
      "parentUUID": "26fe76b2-d17f-4272-a04f-249eaaf602ba",
      "isHook": false,
      "skipped": false
    }
  ],
  "copyrightYear": 2017
}
```

**Comment by ethangodt** [comment] 2017-09-18 23:55
Ok after some more poking around, I'm realizing that this is happening only when we have retries enabled in mocha (specifically, set to `1`).

**Comment by adamgruber** [comment] 2017-09-19 01:15
If it has to do with retries then it may be related to https://github.com/adamgruber/mochawesome/issues/125

**Comment by ethangodt** [comment] 2017-09-19 01:32
@adamgruber thanks for the quick reply. Ouch, that mocha issue has gone stale at this point.

Given you're understanding of mocha and your reporter, do you know if there is any alternative here? Happy to help out if you think it's feasible. We plan to run in retry mode all of the time, so it's a pretty big thing for us.

Thanks again.

**Comment by adamgruber** [comment] 2017-09-19 01:38
The only alternative I've thought about is to not use the `suite end` event to generate the report data and instead listen to each `test` event and build out the data that way since retries will emit events same as any other test. It feels like a pretty big undertaking to fundamentally change how mochawesome gets its data. I could be wrong though and maybe its not as involved as I think.

**Comment by iqianxing** [comment] 2017-11-12 16:22
I meet the same problem on my test report!

**Comment by adamgruber** [comment] 2018-02-02 16:00
Duplicate of #125

**Closed by adamgruber** 2018-02-02 16:00 UTC
