### ISSUE TITLE
Only json file being generated and errors

### ISSUE THREAD

**Issue by jsodeman** [adamgruber/mochawesome#147] opened 2017-04-13 14:37 UTC
Using mocha 3.2.0 and mochawesome 2.0.4 on Node 6.10.0

The console starts with a React warning:
`Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.`

Then the tests run, the .json file is generated and then the following. No other files are generated in the output folder.

```
[mochawesome] Report JSON saved to H:\myproject\mochawesome-reports\mochawesome.json

[mochawesome] {
  "errno": -4058,
  "code": "ENOENT",
  "syscall": "stat",
  "path": "H:\\myproject\\node_modules\\mochawesome-report-generator\\dist\\assets\\external"
}

(node:3316) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: exit is not a function
```

**Comment by jsodeman** [comment] 2017-04-13 14:40
Here's the file

```
const 
	glob = require("glob"),
	Mocha = require("mocha");

const mocha = new Mocha({
	reporter: "mochawesome",
});

glob
	.sync("tests/**/*.test.js")
	.forEach((file) => {
			mocha.addFile(file);
		});

mocha.run();
```

**Comment by adamgruber** [comment] 2017-04-13 16:08
@jsodeman There's a few things going on here:

1. Don't worry about the React warning, it's just a deprecation notice and has nothing to do with your issue.
2. The error you're seeing is because the reporter can't find the `mochawesome-report-generator/dist/assets/external` directory that it needs. Not really sure why this would happen but first thing I'd try is to remove both `mochawesome` and `mochawesome-report-generator` from `node_modules` and then run `npm install` again.
3. Last thing you're seeing, `UnhandledPromiseRejectionWarning`, is an issue I am aware of and will be publishing a fix for soon. It is also just a warning though and has nothing to do with the report being created successfully.

**Comment by jsodeman** [comment] 2017-04-14 04:37
I removed it and tried reinstalling with yarn and npm. With yarn the reporter fails with the error I posted but npm works correctly.

**Comment by adamgruber** [comment] 2017-04-16 13:18
I tried with both yarn and npm and can't reproduce the issue. I'm gonna close this for now but if you can provide a sample project that reproduces it consistently feel free to reopen.

**Closed by adamgruber** 2017-04-16 13:18 UTC
