### ISSUE TITLE
npm install hangs on node > 7

### ISSUE THREAD

**Issue by shane-reaume** [adamgruber/mochawesome#134] opened 2017-02-17 19:52 UTC
I had it timeout many times, then finally it installed today after 4 minutes waiting.

Steps:
1) Remove current so you can see it attempt to install from scratch
2) Install against node 7.5
// observe the slow install and/or timeout

**Comment by adamgruber** [comment] 2017-02-21 13:39
There was an issue with the package size of `mochawesome-report-generator` which should now be fixed. That may have been the cause of your issue. Try to reinstall the latest `mochawesome` and let me know if it is any better.

**Comment by adamgruber** [comment] 2017-04-19 17:33
Closing this issue for the following reason:
- No feedback for more than 30 days

If you are still experiencing this issue, please reopen and provide additional details.

**Closed by adamgruber** 2017-04-19 17:33 UTC
